/**
 * FFI bindings for mylib
 *
 * Auto-generated by Harbour FFI binding generator.
 * Do not edit manually.
 *
 * @packageDocumentation
 */

import koffi from 'koffi';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

// Library path resolution
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Platform-specific library extension
const PLATFORM_EXT: Record<string, string> = {
  'win32': '.dll',
  'darwin': '.dylib',
  'linux': '.so',
};

const libExt = PLATFORM_EXT[process.platform] ?? '.so';
const libPath = join(__dirname, 'libmylib' + libExt);

// Load the native library
const lib = koffi.load(libPath);

export enum mylib_status_t {
  MYLIB_OK = 0,
  MYLIB_ERROR = 1,
  MYLIB_INVALID = 2,
}

export enum mylib_type_t {
  MYLIB_TYPE_INT = 0,
  MYLIB_TYPE_FLOAT = 1,
  MYLIB_TYPE_STRING = 2,
}

const mylib_point_t = koffi.struct('mylib_point_t', {
  x: 'int32',
  y: 'int32',
});

const mylib_item_t = koffi.struct('mylib_item_t', {
  name: 'char*',
  id: 'int32',
  type: 'mylib_type_t',
});

export interface Imylib_point_t {
  x: number;
  y: number;
}

export interface Imylib_item_t {
  name: string | Buffer;
  id: number;
  type: mylib_type_t;
}

// Function bindings
/**
 * @returns number
 */
export const mylib_init = lib.func('mylib_init', 'int32', []) as () => number;

/**
 */
export const mylib_shutdown = lib.func('mylib_shutdown', 'void', []) as () => void;

/**
 * @param a - number
 * @param b - number
 * @returns number
 */
export const mylib_add = lib.func('mylib_add', 'int32', ['int32', 'int32']) as (a: number, b: number) => number;

/**
 * @param input - string
 * @param output - string | Buffer
 * @param output_size - bigint
 * @returns mylib_status_t
 */
export const mylib_process = lib.func('mylib_process', 'mylib_status_t', ['char*', 'char*', 'size_t']) as (input: string, output: string | Buffer, output_size: bigint) => mylib_status_t;

/**
 * @param x - number
 * @param y - number
 * @returns mylib_point_t
 */
export const mylib_create_point = lib.func('mylib_create_point', 'mylib_point_t', ['int32', 'int32']) as (x: number, y: number) => mylib_point_t;

/**
 * @param item - Buffer | number
 */
export const mylib_free_item = lib.func('mylib_free_item', 'void', ['mylib_item_t*']) as (item: Buffer | number) => void;


// Re-export types
export { mylib_point_t };
export { mylib_item_t };
