#!/usr/bin/env python3
"""Derive Harbour.toml content from a package's existing build system.

Writing a native shim for a real C library means knowing exactly which
sources it compiles and with which defines, per platform. That information
already exists -- in openssl's generated Makefile, in a CMake build's
compile_commands.json -- so this reads it rather than guessing, and merges
several platforms' answers into one manifest.

Two rules the extractors follow, both learned the hard way:

* Never skip an object silently. A first pass at this dropped 49 of
  openssl's 1115 x86_64 objects because their sources are generated by
  perlasm at build time and did not exist yet. The result looked like a
  complete harvest and would have produced a library missing every
  optimised AES path. Unresolved objects are an error; a caller that knows
  they are generated says so explicitly.

* Parse argv, not text. `-D` and `-I` appear inside ordinary paths
  (`/Users/x/-Documents/...` matches a naive `-D` regex), so flags are read
  from a properly split argument list.

Usage:

    harvest.py extract-openssl --source DIR --os macos --arch aarch64 -o a.json
    harvest.py extract-cc --file compile_commands.json --source DIR \
        --os linux --arch x86_64 --filter /lib/ -o b.json
    harvest.py merge --package curl --version 8.22.0 a.json b.json -o Harbour.toml
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import re
import shlex
import sys

# --------------------------------------------------------------------------
# extraction
# --------------------------------------------------------------------------

SOURCE_EXTS = (".c", ".S", ".s", ".cc", ".cpp", ".cxx")


def _flags_from_argv(argv: list[str]) -> tuple[set[str], set[str]]:
    """Defines and include dirs from an argument list."""
    defines, includes = set(), set()
    it = iter(range(len(argv)))
    for i in it:
        a = argv[i]
        for prefix, sink in (("-D", defines), ("/D", defines), ("-I", includes), ("/I", includes)):
            if a == prefix:  # value is the next argument
                if i + 1 < len(argv):
                    sink.add(argv[i + 1])
                break
            if a.startswith(prefix) and len(a) > len(prefix):
                sink.add(a[len(prefix):])
                break
    return defines, includes


def extract_openssl(source: str, os_name: str, arch: str) -> dict:
    """Read openssl's generated Makefile.

    openssl archives several separately-flagged product groups into one
    library (its Configure calls them libcrypto, libdefault, libcommon,
    libssl) and the `*_ASM` define sets genuinely differ between them, so
    each group is kept separate here rather than flattened.
    """
    mk_path = os.path.join(source, "Makefile")
    if not os.path.exists(mk_path):
        sys.exit(f"no Makefile in {source}; run its Configure first")
    mk = open(mk_path).read()

    # Global per-object flags live in a variable, not in each rule.
    lib_cppflags = ""
    m = re.search(r"^LIB_CPPFLAGS=(.*)$", mk, re.M)
    if m:
        lib_cppflags = m.group(1)
        for var, val in re.findall(r"^(\w+)=(.*)$", mk, re.M):
            lib_cppflags = lib_cppflags.replace(f"$({var})", val)

    rules = {
        m.group(1): m.group(2)
        for m in re.finditer(r"^(\S+\.o):[^\n]*\n((?:\t[^\n]*\n)+)", mk, re.M)
    }

    # Targets for *generated* sources, with their prerequisites. Consulted
    # rather than guessed: openssl's generators do not follow one layout --
    # `crypto/sha/sha256-x86_64.s` comes from `asm/sha512-x86_64.pl` (one
    # script emits both digests), `crypto/x86_64cpuid.s` from a script beside
    # it rather than under `asm/`, and ten `.c` files from `.c.in` templates.
    # Every guess at those paths was wrong for something.
    gen_rules = {
        m.group(1): m.group(2).split()
        for m in re.finditer(r"^(\S+\.(?:s|S|c|cc))(?::| :)\s*([^\n]*)$", mk, re.M)
    }

    groups: dict[str, dict] = collections.defaultdict(
        lambda: {"sources": [], "defines": None, "include_dirs": set()}
    )
    generated: list[dict] = []

    for lib in ("libcrypto.a", "libssl.a"):
        m = re.search(rf"^{re.escape(lib)}:((?:[^\n]*\\\n)*[^\n]*)", mk, re.M)
        if not m:
            continue
        for obj in re.findall(r"\S+\.o", m.group(1)):
            d, b = os.path.split(obj)
            gm = re.match(r"(lib[a-z0-9]+)-lib-", b)
            group = gm.group(1) if gm else "libcrypto"
            stem = re.sub(r"^lib[a-z0-9]+-lib-", "", b[:-2])

            src = next(
                (
                    os.path.join(d, stem + e)
                    for e in SOURCE_EXTS
                    if os.path.exists(os.path.join(source, d, stem + e))
                ),
                None,
            )
            if src is None:
                # Generated at build time. Ask the Makefile which source it
                # would build and from what, so the caller can add a
                # prebuild step for exactly that.
                target, prereqs = None, []
                for ext in (".s", ".S", ".c", ".cc"):
                    cand = os.path.join(d, stem + ext)
                    if cand in gen_rules:
                        target, prereqs = cand, gen_rules[cand]
                        break
                generated.append(
                    {
                        "object": obj,
                        "expected_source": target,
                        "generated_from": prereqs,
                    }
                )
                continue

            groups[group]["sources"].append(src)
            argv = shlex.split(rules.get(obj, "").replace("\t", " ") + " " + lib_cppflags)
            defs, incs = _flags_from_argv(argv)
            # Intersection: a define only belongs to the group if every
            # object in it gets the define.
            cur = groups[group]["defines"]
            groups[group]["defines"] = defs if cur is None else (cur & defs)
            groups[group]["include_dirs"] |= incs

    return {
        "platform": {"os": os_name, "arch": arch},
        "backend": "openssl-makefile",
        "targets": {
            g: {
                "sources": sorted(v["sources"]),
                "defines": sorted(v["defines"] or set()),
                "include_dirs": sorted(v["include_dirs"]),
            }
            for g, v in groups.items()
        },
        "generated": generated,
    }


def extract_cc(cc_file: str, source: str, os_name: str, arch: str, filt: str | None) -> dict:
    """Read a CMake/Ninja compile_commands.json."""
    entries = json.load(open(cc_file))
    source = os.path.abspath(source)

    sources: list[str] = []
    defines: set | None = None
    includes: set[str] = set()
    external: set[str] = set()

    for e in entries:
        f = os.path.abspath(e["file"])
        if filt and filt not in f.replace(os.sep, "/"):
            continue
        try:
            rel = os.path.relpath(f, source)
        except ValueError:
            continue
        if rel.startswith(".."):
            continue
        sources.append(rel)

        argv = e.get("arguments") or shlex.split(e["command"])
        defs, incs = _flags_from_argv(argv)
        defines = defs if defines is None else (defines & defs)
        for inc in incs:
            abs_inc = os.path.abspath(os.path.join(e.get("directory", "."), inc))
            r = os.path.relpath(abs_inc, source)
            if r.startswith(".."):
                # Outside the package: a generated config dir, or a system
                # dependency the shim must declare deliberately.
                external.add(abs_inc)
            else:
                includes.add(r)

    return {
        "platform": {"os": os_name, "arch": arch},
        "backend": "compile-commands",
        "targets": {
            "main": {
                "sources": sorted(set(sources)),
                "defines": sorted(defines or set()),
                "include_dirs": sorted(includes),
            }
        },
        "external_include_dirs": sorted(external),
        "generated": [],
    }


# --------------------------------------------------------------------------
# merge
# --------------------------------------------------------------------------


def _toml_str(s: str) -> str:
    """Single-quoted where possible: defines carry embedded double quotes."""
    return f"'{s}'" if "'" not in s else '"' + s.replace('"', '\\"') + '"'


def _toml_array(items, indent="  ") -> str:
    if not items:
        return "[]"
    body = "".join(f"{indent}{_toml_str(i)},\n" for i in items)
    return "[\n" + body + "]"


def _condition(platform: dict) -> str:
    return f'arch = "{platform["arch"]}"' if platform["os"] is None else (
        f'os = "{platform["os"]}"\narch = "{platform["arch"]}"'
    )


def _flatten(harvests: list[dict], name: str) -> list[dict]:
    """Union every product group into a single target.

    Harbour links exactly one archive per dependency, so a package whose
    upstream build produces several -- openssl's libcrypto plus libssl --
    cannot be consumed as separate targets. Unioning the defines is safe
    here because upstream already mixes objects compiled with and without
    each `*_ASM` macro into one archive, so none of them decides a shared
    struct layout. The cost is that a consumer wanting only libcrypto still
    links libssl.
    """
    out = []
    for h in harvests:
        merged = {"sources": set(), "defines": set(), "include_dirs": set()}
        for t in h["targets"].values():
            for key in merged:
                merged[key] |= set(t[key])
        out.append(
            {
                **h,
                "targets": {name: {k: sorted(v) for k, v in merged.items()}},
            }
        )
    return out


def merge(
    harvests: list[dict],
    package: str,
    version: str,
    public_include_dirs: list[str] | None = None,
    public_headers: list[str] | None = None,
    baseline: dict | None = None,
) -> str:
    if not harvests:
        sys.exit("nothing to merge")

    # The baseline is checked on the same terms as the rest. It was not, and
    # a baseline harvested from a merely-*configured* tree silently omitted
    # ten template-generated `.c` files, so every platform that fell back to
    # it failed to link on `ossl_der_oid_*`. A baseline with holes is worse
    # than none: it is the thing an unharvested platform relies on.
    for h in harvests + ([baseline] if baseline else []):
        if h["generated"]:
            plat = h["platform"]
            unknown = [g for g in h["generated"] if not g["expected_source"]]
            lines = [
                f"{plat['os']}/{plat['arch']}: {len(h['generated'])} objects are built "
                "from sources that do not exist yet."
            ]
            for g in h["generated"][:3]:
                src = g["expected_source"] or "?"
                frm = ", ".join(g["generated_from"]) or "unknown generator"
                lines.append(f"  {src}  <-  {frm}")
            if len(h["generated"]) > 3:
                lines.append(f"  ... and {len(h['generated']) - 3} more")
            if unknown:
                lines.append(
                    f"{len(unknown)} of them have no rule in the Makefile, so the "
                    "harvest cannot say how to produce them."
                )
            lines += [
                "",
                "Add a [[targets.NAME.prebuild]] step that runs those generators, then",
                "re-harvest once the sources exist. Dropping them silently would produce",
                "a library missing whatever they implement -- for openssl x86_64 that is",
                "every hand-written AES, SHA and bignum path.",
            ]
            sys.exit("\n".join(lines))

    target_names = sorted({t for h in harvests for t in h["targets"]})
    out = [
        f'[package]\nname = "{package}"\nversion = "{version}"\n',
        "# Generated by tools/harvest. Each platform's sources and defines were\n"
        "# read from that platform's own configured build, then merged: what every\n"
        "# platform agrees on is unconditional, and the rest is a `when` block.\n",
    ]

    for name in target_names:
        per = {
            (h["platform"]["os"], h["platform"]["arch"]): h["targets"][name]
            for h in harvests
            if name in h["targets"]
        }
        if baseline is not None and name in baseline["targets"]:
            # The unconditional set is a *portable* build, not the
            # intersection of the platforms harvested.
            #
            # Intersecting was wrong in a way that only shows up on a platform
            # nobody harvested. Assembly *replaces* generic C: openssl's
            # `aes_core.c`, `bn_asm.c`, `camellia.c`, `chacha_enc.c` and
            # `rc4_enc.c` appear in no asm-enabled platform's source list, so
            # an intersection drops them, and an unlisted architecture would
            # compile 1071 files and fail to link. `when` blocks are additive
            # with no "else", so the fallback cannot be expressed as another
            # layer -- the baseline itself has to be the thing that works
            # everywhere, with each architecture *excluding* what its assembly
            # supersedes.
            common = {key: set(baseline["targets"][name][key]) for key in
                      ("sources", "defines", "include_dirs")}
        else:
            common = {
                key: set.intersection(*(set(v[key]) for v in per.values()))
                for key in ("sources", "defines", "include_dirs")
            }

        out.append(f'\n[targets.{name}]\nkind = "staticlib"')
        out.append(f'sources = {_toml_array(sorted(common["sources"]))}')
        if public_headers:
            # Scoping this matters: a package whose `include/` also holds
            # internal trees hands consumers headers that branch on private
            # defines, which Harbour reports as an ABI hazard -- correctly.
            out.append(f"public_headers = {_toml_array(public_headers)}")
        if public_include_dirs:
            out.append(f'\n[targets.{name}.surface.compile.public]')
            out.append(f"include_dirs = {_toml_array(public_include_dirs)}")
        out.append(f'\n[targets.{name}.surface.compile.private]')
        out.append(f'defines = {_toml_array(sorted(common["defines"]))}')
        out.append(f'include_dirs = {_toml_array(sorted(common["include_dirs"]))}')

        shared = len(common["sources"])
        extras = {}
        for plat, vals in sorted(per.items()):
            extras[plat] = {k: set(vals[k]) - common[k] for k in common}
            # Generic sources this platform's assembly supersedes.
            extras[plat]["exclude"] = set(common["sources"]) - set(vals["sources"])
            print(
                f"  {name} {plat[0] or 'any'}/{plat[1]}: {shared} shared sources, "
                f"{len(extras[plat]['sources'])} platform-only, "
                f"{len(extras[plat]['defines'])} platform-only defines",
                file=sys.stderr,
            )

        # Deltas are emitted in layers, general to specific, because `when`
        # blocks are additive: every matching block contributes. openssl's 33
        # aarch64 assembly sources are identical on macOS and Linux while one
        # or two files genuinely differ per OS, so a flat "one block per
        # harvested platform" scheme would either duplicate those 33 lines per
        # OS or -- worse -- gate them on `os = "macos"` and silently drop them
        # on Linux aarch64. A layer per arch plus a small per-platform
        # remainder means each new platform mostly reuses what exists.
        by_arch: dict[str, list[tuple]] = collections.defaultdict(list)
        for plat in extras:
            by_arch[plat[1]].append(plat)

        arch_layer: dict[str, dict] = {}
        for arch, plats in sorted(by_arch.items()):
            if len(plats) < 2:
                continue
            layer = {
                key: set.intersection(*(extras[p][key] for p in plats))
                for key in ("sources", "defines", "include_dirs", "exclude")
            }
            if not any(layer.values()):
                continue
            arch_layer[arch] = layer
            out.append(f'\n[[targets.{name}.when]]')
            out.append(f'arch = "{arch}"')
            for key in ("sources", "exclude", "defines", "include_dirs"):
                if layer[key]:
                    out.append(f"{key} = {_toml_array(sorted(layer[key]))}")

        for plat, extra in sorted(extras.items()):
            layer = arch_layer.get(plat[1], {})
            rest = {
                key: sorted(extra[key] - layer.get(key, set()))
                for key in ("sources", "exclude", "defines", "include_dirs")
            }
            if not any(rest.values()):
                continue
            out.append(f'\n[[targets.{name}.when]]')
            if plat[0]:
                out.append(f'os = "{plat[0]}"')
            out.append(f'arch = "{plat[1]}"')
            for key in ("sources", "exclude", "defines", "include_dirs"):
                if rest[key]:
                    out.append(f"{key} = {_toml_array(rest[key])}")

    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("extract-openssl")
    p.add_argument("--source", required=True)
    p.add_argument("--os", dest="os_name", required=True)
    p.add_argument("--arch", required=True)
    p.add_argument("-o", "--out", required=True)

    p = sub.add_parser("extract-cc")
    p.add_argument("--file", required=True)
    p.add_argument("--source", required=True)
    p.add_argument("--os", dest="os_name", required=True)
    p.add_argument("--arch", required=True)
    p.add_argument("--filter", default=None)
    p.add_argument("-o", "--out", required=True)

    p = sub.add_parser("merge")
    p.add_argument("harvests", nargs="+")
    p.add_argument("--package", required=True)
    p.add_argument("--version", required=True)
    p.add_argument(
        "--flatten-into",
        metavar="TARGET",
        help="union every product group into one target of this name; needed "
        "when upstream produces several archives, since Harbour links one "
        "archive per dependency",
    )
    p.add_argument(
        "--public-include-dir",
        action="append",
        default=[],
        help="directory consumers compile against (repeatable). Not inferable "
        "from a build system, which only records what the library itself uses.",
    )
    p.add_argument(
        "--public-headers",
        action="append",
        default=[],
        help="glob for the genuinely public headers (repeatable), e.g. "
        "include/openssl/**/*.h",
    )
    p.add_argument(
        "--baseline",
        metavar="HARVEST",
        action="append",
        default=[],
        help="harvest of a portable build (e.g. openssl configured `no-asm`) "
        "to use as the unconditional set, so a platform nobody harvested "
        "still builds. Without it the unconditional set is the intersection "
        "of the harvests, which drops the generic C that assembly replaces. "
        "Repeat once per OS: a single Configure run is portable in its "
        "*architecture* only, and still carries that OS's own sources -- a "
        "Linux no-asm baseline drags in `engines/e_afalg.c`, which needs "
        "linux/version.h and breaks every other OS. The baselines are "
        "intersected.",
    )
    p.add_argument("-o", "--out", required=True)

    a = ap.parse_args()

    if a.cmd == "extract-openssl":
        data = extract_openssl(a.source, a.os_name, a.arch)
    elif a.cmd == "extract-cc":
        data = extract_cc(a.file, a.source, a.os_name, a.arch, a.filter)
    else:
        harvests = [json.load(open(f)) for f in a.harvests]
        baseline = None
        if a.baseline:
            baselines = [json.load(open(f)) for f in a.baseline]
            baseline = baselines[0]
            for other in baselines[1:]:
                for name, t in list(baseline["targets"].items()):
                    o = other["targets"].get(name, {"sources": [], "defines": [], "include_dirs": []})
                    for key in ("sources", "defines", "include_dirs"):
                        t[key] = sorted(set(t[key]) & set(o[key]))
        if a.flatten_into:
            harvests = _flatten(harvests, a.flatten_into)
            # The baseline has to be flattened under the same name, or the
            # merge looks it up by a target that no longer exists and
            # silently falls back to intersecting.
            if baseline is not None:
                baseline = _flatten([baseline], a.flatten_into)[0]
        open(a.out, "w").write(
            merge(
                harvests,
                a.package,
                a.version,
                a.public_include_dir,
                a.public_headers,
                baseline,
            )
        )
        print(f"wrote {a.out}")
        return

    json.dump(data, open(a.out, "w"), indent=2)
    n = sum(len(t["sources"]) for t in data["targets"].values())
    print(f"wrote {a.out}: {n} sources, {len(data['generated'])} generated")


if __name__ == "__main__":
    main()
