#!/usr/bin/env python3
"""Derive Harbour.toml content from a package's existing build system.

Writing a native shim for a real C library means knowing exactly which
sources it compiles and with which defines, per platform. That information
already exists -- in openssl's generated Makefile, in a CMake build's
compile_commands.json -- so this reads it rather than guessing, and merges
several platforms' answers into one manifest.

Two rules the extractors follow, both learned the hard way:

* Never skip an object silently. A first pass at this dropped 49 of
  openssl's 1115 x86_64 objects because their sources are generated by
  perlasm at build time and did not exist yet. The result looked like a
  complete harvest and would have produced a library missing every
  optimised AES path. Unresolved objects are an error; a caller that knows
  they are generated says so explicitly.

* Parse argv, not text. `-D` and `-I` appear inside ordinary paths
  (`/Users/x/-Documents/...` matches a naive `-D` regex), so flags are read
  from a properly split argument list.

Usage:

    harvest.py extract-openssl --source DIR --os macos --arch aarch64 -o a.json
    harvest.py extract-cc --file compile_commands.json --source DIR \
        --os linux --arch x86_64 --filter /lib/ -o b.json
    harvest.py merge --package curl --version 8.22.0 a.json b.json -o Harbour.toml
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import re
import shlex
import sys

# --------------------------------------------------------------------------
# extraction
# --------------------------------------------------------------------------

SOURCE_EXTS = (".c", ".S", ".s", ".cc", ".cpp", ".cxx")


def _flags_from_argv(argv: list[str]) -> tuple[set[str], set[str]]:
    """Defines and include dirs from an argument list."""
    defines, includes = set(), set()
    it = iter(range(len(argv)))
    for i in it:
        a = argv[i]
        for prefix, sink in (("-D", defines), ("/D", defines), ("-I", includes), ("/I", includes)):
            if a == prefix:  # value is the next argument
                if i + 1 < len(argv):
                    sink.add(argv[i + 1])
                break
            if a.startswith(prefix) and len(a) > len(prefix):
                sink.add(a[len(prefix):])
                break
    return defines, includes


def _make_vars(mk: str) -> dict[str, str]:
    """`NAME=value` from a Makefile, with `$(NAME)` references expanded.

    Shallow on purpose: enough to turn `$(PERL) x.pl "$(PERLASM_SCHEME)"` into
    `perl x.pl "ios64"`. A generated recipe that still contains `$(` after
    this is reported rather than guessed at -- see `_generator_command`.
    """
    raw = dict(re.findall(r"^(\w+)=(.*)$", mk, re.M))
    out = {}
    for name, value in raw.items():
        for _ in range(8):
            expanded = re.sub(r"\$\((\w+)\)", lambda m: raw.get(m.group(1), ""), value)
            if expanded == value:
                break
            value = expanded
        out[name] = value.strip()
    return out


def _generator_command(target: str, recipe: list[str], make_vars: dict[str, str]) -> dict | None:
    """Turn one Makefile recipe into a `[[targets.X.prebuild]]` block.

    Only the perlasm shape is recognised, and deliberately so:

        CC="$(CC)" $(PERL) crypto/sha/asm/sha512-armv8.pl "$(PERLASM_SCHEME)" \
            -Icrypto -I. ... -DSHA256_ASM ... $(PROCESSOR) $@

    which is one program, plain arguments, one output. openssl's *other*
    generators -- the `.c.in`/`.h.in` templates -- end in `> $@`, and a
    `prebuild` step has no shell and therefore no redirection, so there is
    nothing faithful to emit for them and this returns None rather than
    inventing a `sh -c`. The caller reports them by name; for the templates
    the answer is `util/dofile.pl -i.in`, which writes the file itself.

    The host's `CC` is *not* baked in: an absolute compiler path in a
    committed manifest is wrong on every other machine. The env carries plain
    `cc`, which is what openssl's own `CC=$(CROSS_COMPILE)cc` default means.
    """
    if len(recipe) != 1:
        return None
    line = recipe[0].replace("$@", target)
    for _ in range(8):
        expanded = re.sub(r"\$\((\w+)\)", lambda m: make_vars.get(m.group(1), ""), line)
        if expanded == line:
            break
        line = expanded
    if "$" in line or ">" in line or "|" in line or "&&" in line or ";" in line:
        return None

    argv = shlex.split(line)
    env = {}
    while argv and re.fullmatch(r"\w+=.*", argv[0]):
        key, _, value = argv[0].partition("=")
        # Never record a discovered absolute toolchain path.
        env[key] = "cc" if key == "CC" else value
        argv.pop(0)
    if not argv or os.path.basename(argv[0]) != "perl":
        return None
    if target not in argv[1:]:
        # The recipe must actually name the file it is declared to produce,
        # or `outputs` would be a claim rather than a check.
        return None

    # The recipe's own arguments are kept verbatim apart from one class:
    # anything carrying an absolute path. openssl's perlasm invocations
    # inherit the whole library flag set, which includes
    # `-DOPENSSLDIR="/usr/local/ssl"` and, on macOS, the SDK path -- values
    # from the harvesting machine that would be wrong in a committed
    # manifest. They are dropped and reported, not silently kept.
    #
    # Everything else stays, including flags a perl script has no use for
    # (`-O3`, `-Wall`), because *some* of openssl's scripts do read their
    # tail: `aes-586.pl` tests whether the last argument is `386`. Pruning
    # by usefulness would need to know which script cares.
    args, dropped = [], []
    for a in argv[1:]:
        (dropped if re.search(r"(^|=|\")/", a) else args).append(a)

    block = {"program": "perl", "args": args, "outputs": [target]}
    if env:
        block["env"] = env
    if dropped:
        block["dropped_args"] = dropped
    return block


def extract_openssl(source: str, os_name: str, arch: str) -> dict:
    """Read openssl's generated Makefile.

    openssl archives several separately-flagged product groups into one
    library (its Configure calls them libcrypto, libdefault, libcommon,
    libssl) and the `*_ASM` define sets genuinely differ between them, so
    each group is kept separate here rather than flattened.
    """
    mk_path = os.path.join(source, "Makefile")
    if not os.path.exists(mk_path):
        sys.exit(f"no Makefile in {source}; run its Configure first")
    mk = open(mk_path).read()

    # Global per-object flags live in a variable, not in each rule.
    lib_cppflags = ""
    m = re.search(r"^LIB_CPPFLAGS=(.*)$", mk, re.M)
    if m:
        lib_cppflags = m.group(1)
        for var, val in re.findall(r"^(\w+)=(.*)$", mk, re.M):
            lib_cppflags = lib_cppflags.replace(f"$({var})", val)

    rules = {
        m.group(1): m.group(2)
        for m in re.finditer(r"^(\S+\.o):[^\n]*\n((?:\t[^\n]*\n)+)", mk, re.M)
    }

    # Targets for *generated* sources, with their prerequisites. Consulted
    # rather than guessed: openssl's generators do not follow one layout --
    # `crypto/sha/sha256-x86_64.s` comes from `asm/sha512-x86_64.pl` (one
    # script emits both digests), `crypto/x86_64cpuid.s` from a script beside
    # it rather than under `asm/`, and ten `.c` files from `.c.in` templates.
    # Every guess at those paths was wrong for something.
    gen_rules = {
        m.group(1): m.group(2).split()
        for m in re.finditer(r"^(\S+\.(?:s|S|c|cc))(?::| :)\s*([^\n]*)$", mk, re.M)
    }

    # ... and their *recipes*, which is what a `prebuild` step has to
    # reproduce. The prerequisite list alone is not enough: the flavour
    # (`ios64`, `elf`, `macosx`) lives only in the recipe, and it is not
    # cosmetic -- it decides symbol decoration and section directives, so a
    # macOS build handed `elf` assembles to objects the linker rejects.
    gen_recipes = {
        m.group(1): [ln.strip() for ln in m.group(2).strip("\n").split("\n")]
        for m in re.finditer(
            r"^(\S+\.(?:s|S|c|cc))(?::| :)[^\n]*\n((?:\t[^\n]*\n)+)", mk, re.M
        )
    }
    make_vars = _make_vars(mk)

    groups: dict[str, dict] = collections.defaultdict(
        lambda: {"sources": [], "defines": None, "include_dirs": set()}
    )
    generated: list[dict] = []

    for lib in ("libcrypto.a", "libssl.a"):
        m = re.search(rf"^{re.escape(lib)}:((?:[^\n]*\\\n)*[^\n]*)", mk, re.M)
        if not m:
            continue
        for obj in re.findall(r"\S+\.o", m.group(1)):
            d, b = os.path.split(obj)
            gm = re.match(r"(lib[a-z0-9]+)-lib-", b)
            group = gm.group(1) if gm else "libcrypto"
            stem = re.sub(r"^lib[a-z0-9]+-lib-", "", b[:-2])

            src = next(
                (
                    os.path.join(d, stem + e)
                    for e in SOURCE_EXTS
                    if os.path.exists(os.path.join(source, d, stem + e))
                ),
                None,
            )
            if src is None:
                # Generated at build time. Ask the Makefile which source it
                # would build and from what, so the caller can add a
                # prebuild step for exactly that.
                target, prereqs = None, []
                for ext in (".s", ".S", ".c", ".cc"):
                    cand = os.path.join(d, stem + ext)
                    if cand in gen_rules:
                        target, prereqs = cand, gen_rules[cand]
                        break
                generated.append(
                    {
                        "object": obj,
                        "expected_source": target,
                        "generated_from": prereqs,
                        "prebuild": (
                            _generator_command(
                                target, gen_recipes.get(target, []), make_vars
                            )
                            if target
                            else None
                        ),
                    }
                )
                continue

            groups[group]["sources"].append(src)
            argv = shlex.split(rules.get(obj, "").replace("\t", " ") + " " + lib_cppflags)
            defs, incs = _flags_from_argv(argv)
            # Intersection: a define only belongs to the group if every
            # object in it gets the define.
            cur = groups[group]["defines"]
            groups[group]["defines"] = defs if cur is None else (cur & defs)
            groups[group]["include_dirs"] |= incs

    return {
        "platform": {"os": os_name, "arch": arch},
        "backend": "openssl-makefile",
        "targets": {
            g: {
                "sources": sorted(v["sources"]),
                "defines": sorted(v["defines"] or set()),
                "include_dirs": sorted(v["include_dirs"]),
            }
            for g, v in groups.items()
        },
        "generated": generated,
    }


def extract_cc(cc_file: str, source: str, os_name: str, arch: str, filt: str | None) -> dict:
    """Read a CMake/Ninja compile_commands.json."""
    entries = json.load(open(cc_file))
    source = os.path.abspath(source)

    sources: list[str] = []
    defines: set | None = None
    includes: set[str] = set()
    external: set[str] = set()

    for e in entries:
        f = os.path.abspath(e["file"])
        if filt and filt not in f.replace(os.sep, "/"):
            continue
        try:
            rel = os.path.relpath(f, source)
        except ValueError:
            continue
        if rel.startswith(".."):
            continue
        sources.append(rel)

        argv = e.get("arguments") or shlex.split(e["command"])
        defs, incs = _flags_from_argv(argv)
        defines = defs if defines is None else (defines & defs)
        for inc in incs:
            abs_inc = os.path.abspath(os.path.join(e.get("directory", "."), inc))
            r = os.path.relpath(abs_inc, source)
            if r.startswith(".."):
                # Outside the package: a generated config dir, or a system
                # dependency the shim must declare deliberately.
                external.add(abs_inc)
            else:
                includes.add(r)

    return {
        "platform": {"os": os_name, "arch": arch},
        "backend": "compile-commands",
        "targets": {
            "main": {
                "sources": sorted(set(sources)),
                "defines": sorted(defines or set()),
                "include_dirs": sorted(includes),
            }
        },
        "external_include_dirs": sorted(external),
        "generated": [],
    }


# --------------------------------------------------------------------------
# merge
# --------------------------------------------------------------------------


def _toml_str(s: str) -> str:
    """Single-quoted where possible: defines carry embedded double quotes."""
    return f"'{s}'" if "'" not in s else '"' + s.replace('"', '\\"') + '"'


def _toml_array(items, indent="  ") -> str:
    if not items:
        return "[]"
    body = "".join(f"{indent}{_toml_str(i)},\n" for i in items)
    return "[\n" + body + "]"


def _condition(platform: dict) -> str:
    return f'arch = "{platform["arch"]}"' if platform["os"] is None else (
        f'os = "{platform["os"]}"\narch = "{platform["arch"]}"'
    )


def _flatten(harvests: list[dict], name: str) -> list[dict]:
    """Union every product group into a single target.

    Harbour links exactly one archive per dependency, so a package whose
    upstream build produces several -- openssl's libcrypto plus libssl --
    cannot be consumed as separate targets. Unioning the defines is safe
    here because upstream already mixes objects compiled with and without
    each `*_ASM` macro into one archive, so none of them decides a shared
    struct layout. The cost is that a consumer wanting only libcrypto still
    links libssl.
    """
    out = []
    for h in harvests:
        merged = {"sources": set(), "defines": set(), "include_dirs": set()}
        for t in h["targets"].values():
            for key in merged:
                merged[key] |= set(t[key])
        out.append(
            {
                **h,
                "targets": {name: {k: sorted(v) for k, v in merged.items()}},
            }
        )
    return out


def merge(
    harvests: list[dict],
    package: str,
    version: str,
    public_include_dirs: list[str] | None = None,
    public_headers: list[str] | None = None,
    baseline: dict | None = None,
    emit_prebuild: bool = False,
) -> str:
    if not harvests:
        sys.exit("nothing to merge")

    # With `--emit-prebuild`, a generated source stops being a reason to
    # refuse and becomes a `[[targets.X.when.prebuild]]` step plus a source
    # in that platform's layer. This is what makes a package whose assembly
    # does not exist in the tarball -- openssl, all of it -- expressible
    # without vendoring 5.6 MB of generated `.s` per architecture.
    #
    # The refusal stays for anything whose recipe cannot be reproduced
    # faithfully (see `_generator_command`), because a manifest that
    # generates *most* of the assembly is the silent-degradation failure
    # this tool exists to prevent: it links, and it computes correct
    # answers, slowly, with no witness.
    prebuilds: dict[tuple, list[dict]] = collections.defaultdict(list)
    if emit_prebuild:
        for h in harvests + ([baseline] if baseline else []):
            plat = (h["platform"]["os"], h["platform"]["arch"])
            still_generated = []
            for g in h["generated"]:
                block = g.get("prebuild")
                if not block:
                    still_generated.append(g)
                    continue
                if h is not baseline:
                    prebuilds[plat].append(block)
                    if block.get("dropped_args"):
                        print(
                            f"  note: {g['expected_source']}: dropped "
                            f"{len(block['dropped_args'])} generator argument(s) "
                            "carrying an absolute path from the harvesting machine "
                            f"({', '.join(block['dropped_args'][:2])}...)",
                            file=sys.stderr,
                        )
                # The file the generator writes is a source of this platform
                # on the same terms as any other, so it goes through the
                # same layering below.
                #
                # Which product group it belongs to is not recoverable here
                # (the object name records it, the rule does not), so it
                # lands in the first target that does not already have it.
                # That is exact for the case this is used in: Harbour links
                # one archive per dependency, so openssl is merged with
                # `--flatten-into` and there is only one target by the time
                # this runs. Without flattening it is a guess, and a package
                # with several archives cannot be consumed anyway.
                for t in h["targets"].values():
                    if g["expected_source"] not in t["sources"]:
                        t["sources"] = sorted(set(t["sources"]) | {g["expected_source"]})
                        break
            h["generated"] = still_generated

    # The baseline is checked on the same terms as the rest. It was not, and
    # a baseline harvested from a merely-*configured* tree silently omitted
    # ten template-generated `.c` files, so every platform that fell back to
    # it failed to link on `ossl_der_oid_*`. A baseline with holes is worse
    # than none: it is the thing an unharvested platform relies on.
    for h in harvests + ([baseline] if baseline else []):
        if h["generated"]:
            plat = h["platform"]
            unknown = [g for g in h["generated"] if not g["expected_source"]]
            lines = [
                f"{plat['os']}/{plat['arch']}: {len(h['generated'])} objects are built "
                "from sources that do not exist yet."
            ]
            for g in h["generated"][:3]:
                src = g["expected_source"] or "?"
                frm = ", ".join(g["generated_from"]) or "unknown generator"
                lines.append(f"  {src}  <-  {frm}")
            if len(h["generated"]) > 3:
                lines.append(f"  ... and {len(h['generated']) - 3} more")
            if unknown:
                lines.append(
                    f"{len(unknown)} of them have no rule in the Makefile, so the "
                    "harvest cannot say how to produce them."
                )
            lines += [
                "",
                "Pass --emit-prebuild to have merge write the [[targets.NAME.when.prebuild]]",
                "steps that run these generators, from the recipes in the build system's own",
                "rules. Anything still listed above has a recipe that cannot be reproduced",
                "faithfully -- openssl's `.c.in`/`.h.in` templates end in `> $@`, and a",
                "prebuild step has no shell and so no redirection; for those, use",
                "`util/dofile.pl -i.in FILE.in`, which writes the file itself.",
                "",
                "Dropping them silently would produce a library missing whatever they",
                "implement -- for openssl x86_64 that is every hand-written AES, SHA and",
                "bignum path, and it would still link and still compute correct answers.",
            ]
            sys.exit("\n".join(lines))

    target_names = sorted({t for h in harvests for t in h["targets"]})
    out = [
        f'[package]\nname = "{package}"\nversion = "{version}"\n',
        "# Generated by tools/harvest. Each platform's sources and defines were\n"
        "# read from that platform's own configured build, then merged: what every\n"
        "# platform agrees on is unconditional, and the rest is a `when` block.\n",
    ]

    for name in target_names:
        per = {
            (h["platform"]["os"], h["platform"]["arch"]): h["targets"][name]
            for h in harvests
            if name in h["targets"]
        }
        if baseline is not None and name in baseline["targets"]:
            # The unconditional set is a *portable* build, not the
            # intersection of the platforms harvested.
            #
            # Intersecting was wrong in a way that only shows up on a platform
            # nobody harvested. Assembly *replaces* generic C: openssl's
            # `aes_core.c`, `bn_asm.c`, `camellia.c`, `chacha_enc.c` and
            # `rc4_enc.c` appear in no asm-enabled platform's source list, so
            # an intersection drops them, and an unlisted architecture would
            # compile 1071 files and fail to link. `when` blocks are additive
            # with no "else", so the fallback cannot be expressed as another
            # layer -- the baseline itself has to be the thing that works
            # everywhere, with each architecture *excluding* what its assembly
            # supersedes.
            common = {key: set(baseline["targets"][name][key]) for key in
                      ("sources", "defines", "include_dirs")}
        else:
            common = {
                key: set.intersection(*(set(v[key]) for v in per.values()))
                for key in ("sources", "defines", "include_dirs")
            }

        out.append(f'\n[targets.{name}]\nkind = "staticlib"')
        out.append(f'sources = {_toml_array(sorted(common["sources"]))}')
        if public_headers:
            # Scoping this matters: a package whose `include/` also holds
            # internal trees hands consumers headers that branch on private
            # defines, which Harbour reports as an ABI hazard -- correctly.
            out.append(f"public_headers = {_toml_array(public_headers)}")
        if public_include_dirs:
            out.append(f'\n[targets.{name}.surface.compile.public]')
            out.append(f"include_dirs = {_toml_array(public_include_dirs)}")
        out.append(f'\n[targets.{name}.surface.compile.private]')
        out.append(f'defines = {_toml_array(sorted(common["defines"]))}')
        out.append(f'include_dirs = {_toml_array(sorted(common["include_dirs"]))}')

        shared = len(common["sources"])
        extras = {}
        for plat, vals in sorted(per.items()):
            extras[plat] = {k: set(vals[k]) - common[k] for k in common}
            # Generic sources this platform's assembly supersedes.
            extras[plat]["exclude"] = set(common["sources"]) - set(vals["sources"])
            print(
                f"  {name} {plat[0] or 'any'}/{plat[1]}: {shared} shared sources, "
                f"{len(extras[plat]['sources'])} platform-only, "
                f"{len(extras[plat]['defines'])} platform-only defines",
                file=sys.stderr,
            )

        # Deltas are emitted in layers, general to specific, because `when`
        # blocks are additive: every matching block contributes. openssl's 33
        # aarch64 assembly sources are identical on macOS and Linux while one
        # or two files genuinely differ per OS, so a flat "one block per
        # harvested platform" scheme would either duplicate those 33 lines per
        # OS or -- worse -- gate them on `os = "macos"` and silently drop them
        # on Linux aarch64.
        #
        # Which axis cuts across the platforms is a property of the package,
        # not a constant. openssl's is the architecture (assembly). libuv's is
        # the *OS*: `src/unix/linux.c` and friends are the same four files on
        # every Linux architecture. An arch-only layering scheme emits those
        # four under `os = "linux", arch = "x86_64"` and again under
        # `os = "linux", arch = "aarch64"`, which is the very failure the
        # paragraph above describes, one axis over: linux/riscv64 then matches
        # no block and fails to link, on a package that supports it.
        #
        # So both axes are candidates, and each item is attached to the
        # coarsest condition whose harvested platforms all want it. An item
        # every platform wants is already unconditional (it survived the
        # intersection), so what is left here genuinely varies.
        plats = sorted(extras)
        candidates: list[tuple[str | None, str | None]] = []
        candidates += [(None, a) for a in sorted({p[1] for p in plats if p[1]})]
        candidates += [(o, None) for o in sorted({p[0] for p in plats if p[0]})]
        candidates += plats

        def covered(cond: tuple) -> set:
            o, a = cond
            return {
                p for p in plats
                if (o is None or p[0] == o) and (a is None or p[1] == a)
            }

        # Coarsest first, with a deterministic tie-break: a two-platform arch
        # layer and a two-platform os layer are equally general, so the order
        # of the emitted file must not depend on set iteration order.
        ranked = sorted(candidates, key=lambda c: (-len(covered(c)), str(c)))

        layers: dict[tuple, dict[str, list[str]]] = collections.defaultdict(
            lambda: collections.defaultdict(list)
        )
        for key in ("sources", "exclude", "defines", "include_dirs"):
            for item in sorted({i for p in plats for i in extras[p][key]}):
                want = {p for p in plats if item in extras[p][key]}
                # Tile `want` with candidate conditions. A single-platform
                # candidate always qualifies, so this terminates.
                while want:
                    cond = next(c for c in ranked if covered(c) and covered(c) <= want)
                    layers[cond][key].append(item)
                    want -= covered(cond)

        # A generator is attached to the exact (os, arch) it was harvested
        # from, never to a coarser layer, because the flavour argument is
        # per-OS -- while the *source* it writes is usually wanted on every
        # architecture of its kind and does get layered. That asymmetry is
        # the whole reason the two are emitted separately: openssl's 33 arm
        # assembly files are one `arch = "aarch64"` block, and the perl
        # invocations that write them are two, one per OS.
        emitted = [c for c in ranked if c in layers or c in prebuilds]
        for cond in emitted:
            os_name, arch = cond
            out.append(f'\n[[targets.{name}.when]]')
            if os_name:
                out.append(f'os = "{os_name}"')
            if arch:
                out.append(f'arch = "{arch}"')
            for key in ("sources", "exclude", "defines", "include_dirs"):
                if layers[cond][key]:
                    out.append(f"{key} = {_toml_array(sorted(layers[cond][key]))}")
            # Sub-tables last: every key above belongs to the `when` block,
            # and TOML closes that block as soon as a sub-table opens.
            for block in prebuilds.get(cond, []):
                out.append(f'\n[[targets.{name}.when.prebuild]]')
                out.append(f'program = {_toml_str(block["program"])}')
                out.append(f'args = {_toml_array(block["args"])}')
                out.append(f'outputs = {_toml_array(block["outputs"])}')
                if block.get("env"):
                    kv = ", ".join(
                        f"{k} = {_toml_str(v)}" for k, v in sorted(block["env"].items())
                    )
                    out.append(f"env = {{ {kv} }}")

    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("extract-openssl")
    p.add_argument("--source", required=True)
    p.add_argument("--os", dest="os_name", required=True)
    p.add_argument("--arch", required=True)
    p.add_argument("-o", "--out", required=True)

    p = sub.add_parser("extract-cc")
    p.add_argument("--file", required=True)
    p.add_argument("--source", required=True)
    p.add_argument("--os", dest="os_name", required=True)
    p.add_argument("--arch", required=True)
    p.add_argument("--filter", default=None)
    p.add_argument("-o", "--out", required=True)

    p = sub.add_parser("merge")
    p.add_argument("harvests", nargs="+")
    p.add_argument("--package", required=True)
    p.add_argument("--version", required=True)
    p.add_argument(
        "--flatten-into",
        metavar="TARGET",
        help="union every product group into one target of this name; needed "
        "when upstream produces several archives, since Harbour links one "
        "archive per dependency",
    )
    p.add_argument(
        "--public-include-dir",
        action="append",
        default=[],
        help="directory consumers compile against (repeatable). Not inferable "
        "from a build system, which only records what the library itself uses.",
    )
    p.add_argument(
        "--public-headers",
        action="append",
        default=[],
        help="glob for the genuinely public headers (repeatable), e.g. "
        "include/openssl/**/*.h",
    )
    p.add_argument(
        "--baseline",
        metavar="HARVEST",
        action="append",
        default=[],
        help="harvest of a portable build (e.g. openssl configured `no-asm`) "
        "to use as the unconditional set, so a platform nobody harvested "
        "still builds. Without it the unconditional set is the intersection "
        "of the harvests, which drops the generic C that assembly replaces. "
        "Repeat once per OS: a single Configure run is portable in its "
        "*architecture* only, and still carries that OS's own sources -- a "
        "Linux no-asm baseline drags in `engines/e_afalg.c`, which needs "
        "linux/version.h and breaks every other OS. The baselines are "
        "intersected.",
    )
    p.add_argument(
        "--emit-prebuild",
        action="store_true",
        help="write [[targets.NAME.when.prebuild]] steps for sources the build "
        "system generates, taken from its own recipes, instead of refusing. "
        "Needed by any package whose assembly does not exist in the tarball -- "
        "openssl's is perlasm-generated on every platform. Recipes that need a "
        "shell (openssl's `.c.in` templates redirect to `> $@`) are still "
        "refused, because a manifest that generates most of the assembly links "
        "and computes correct answers with no witness.",
    )
    p.add_argument("-o", "--out", required=True)

    a = ap.parse_args()

    if a.cmd == "extract-openssl":
        data = extract_openssl(a.source, a.os_name, a.arch)
    elif a.cmd == "extract-cc":
        data = extract_cc(a.file, a.source, a.os_name, a.arch, a.filter)
    else:
        harvests = [json.load(open(f)) for f in a.harvests]
        baseline = None
        if a.baseline:
            baselines = [json.load(open(f)) for f in a.baseline]
            baseline = baselines[0]
            for other in baselines[1:]:
                for name, t in list(baseline["targets"].items()):
                    o = other["targets"].get(name, {"sources": [], "defines": [], "include_dirs": []})
                    for key in ("sources", "defines", "include_dirs"):
                        t[key] = sorted(set(t[key]) & set(o[key]))
        if a.flatten_into:
            harvests = _flatten(harvests, a.flatten_into)
            # The baseline has to be flattened under the same name, or the
            # merge looks it up by a target that no longer exists and
            # silently falls back to intersecting.
            if baseline is not None:
                baseline = _flatten([baseline], a.flatten_into)[0]
        open(a.out, "w").write(
            merge(
                harvests,
                a.package,
                a.version,
                a.public_include_dir,
                a.public_headers,
                baseline,
                a.emit_prebuild,
            )
        )
        print(f"wrote {a.out}")
        return

    json.dump(data, open(a.out, "w"), indent=2)
    n = sum(len(t["sources"]) for t in data["targets"].values())
    print(f"wrote {a.out}: {n} sources, {len(data['generated'])} generated")


if __name__ == "__main__":
    main()
